Maint/CICD ~ (GHA) disable style/spell-check automation

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -133,48 +133,48 @@ jobs:
           S=$(cargo clippy --all-targets ${{ matrix.job.cargo-options }} ${{ steps.vars.outputs.CARGO_FEATURES_OPTION }} -- -D warnings 2>&1) && printf "%s\n" "$S" || { printf "%s\n" "$S" ; printf "%s" "$S" | sed -E -n -e '/^error:/{' -e "N; s/^error:[[:space:]]+(.*)\\n[[:space:]]+-->[[:space:]]+(.*):([0-9]+):([0-9]+).*$/::${fault_type} file=\2,line=\3,col=\4::${fault_prefix}: \`cargo clippy\`: \1 (file:'\2', line:\3)/p;" -e '}' ; fault=true ; }
           if [ -n "${{ steps.vars.outputs.FAIL_ON_FAULT }}" ] && [ -n "$fault" ]; then exit 1 ; fi
 
-  style_spellcheck:
-    name: Style/spelling
-    runs-on: ${{ matrix.job.os }}
-    env:
-      STYLE_FAIL_ON_FAULT: false # overrides workflow default
-    strategy:
-      matrix:
-        job:
-          - { os: ubuntu-latest }
-    steps:
-      - uses: actions/checkout@v2
-      - name: Initialize workflow variables
-        id: vars
-        shell: bash
-        run: |
-          ## VARs setup
-          outputs() { step_id="vars"; for var in "$@" ; do echo steps.${step_id}.outputs.${var}="${!var}"; echo ::set-output name=${var}::${!var}; done; }
-          # failure mode
-          unset FAIL_ON_FAULT ; case '${{ env.STYLE_FAIL_ON_FAULT }}' in
-            ''|0|f|false|n|no|off) FAULT_TYPE=warning ;;
-            *) FAIL_ON_FAULT=true ; FAULT_TYPE=error ;;
-          esac;
-          outputs FAIL_ON_FAULT FAULT_TYPE
-      - name: Install/setup prerequisites
-        shell: bash
-        run: |
-          ## Install/setup prerequisites
-          sudo apt-get -y update ; sudo apt-get -y install npm ; sudo npm install cspell -g ;
-      - name: Run `cspell`
-        shell: bash
-        run: |
-          ## Run `cspell`
-          unset fault
-          fault_type="${{ steps.vars.outputs.FAULT_TYPE }}"
-          fault_prefix=$(echo "$fault_type" | tr '[:lower:]' '[:upper:]')
-          # * find cspell configuration
-          cfg_files=($(shopt -s nullglob ; echo {.vscode,.}/{,.}c[sS]pell{.json,.config{.js,.cjs,.json,.yaml,.yml},.yaml,.yml} ;))
-          cfg_file=${cfg_files[0]}
-          unset CSPELL_CFG_OPTION ; if [ -n "$cfg_file" ]; then CSPELL_CFG_OPTION="--config \"$cfg_file\"" ; fi
-          # * `cspell`
-          S=$(cspell ${CSPELL_CFG_OPTION} --no-summary --no-progress "**/*") && printf "%s\n" "$S" || { printf "%s\n" "$S" ; printf "%s" "$S" | sed -E -n "s/${PWD//\//\\/}\/(.*):(.*):(.*) - (.*)/::${fault_type} file=\1,line=\2,col=\3::${fault_type^^}: \4 (file:'\1', line:\2)/p" ; fault=true ; true ; }
-          if [ -n "${{ steps.vars.outputs.FAIL_ON_FAULT }}" ] && [ -n "$fault" ]; then exit 1 ; fi
+  # style_spellcheck:
+  #   name: Style/spelling
+  #   runs-on: ${{ matrix.job.os }}
+  #   env:
+  #     STYLE_FAIL_ON_FAULT: false # overrides workflow default
+  #   strategy:
+  #     matrix:
+  #       job:
+  #         - { os: ubuntu-latest }
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: Initialize workflow variables
+  #       id: vars
+  #       shell: bash
+  #       run: |
+  #         ## VARs setup
+  #         outputs() { step_id="vars"; for var in "$@" ; do echo steps.${step_id}.outputs.${var}="${!var}"; echo ::set-output name=${var}::${!var}; done; }
+  #         # failure mode
+  #         unset FAIL_ON_FAULT ; case '${{ env.STYLE_FAIL_ON_FAULT }}' in
+  #           ''|0|f|false|n|no|off) FAULT_TYPE=warning ;;
+  #           *) FAIL_ON_FAULT=true ; FAULT_TYPE=error ;;
+  #         esac;
+  #         outputs FAIL_ON_FAULT FAULT_TYPE
+  #     - name: Install/setup prerequisites
+  #       shell: bash
+  #       run: |
+  #         ## Install/setup prerequisites
+  #         sudo apt-get -y update ; sudo apt-get -y install npm ; sudo npm install cspell -g ;
+  #     - name: Run `cspell`
+  #       shell: bash
+  #       run: |
+  #         ## Run `cspell`
+  #         unset fault
+  #         fault_type="${{ steps.vars.outputs.FAULT_TYPE }}"
+  #         fault_prefix=$(echo "$fault_type" | tr '[:lower:]' '[:upper:]')
+  #         # * find cspell configuration
+  #         cfg_files=($(shopt -s nullglob ; echo {.vscode,.}/{,.}c[sS]pell{.json,.config{.js,.cjs,.json,.yaml,.yml},.yaml,.yml} ;))
+  #         cfg_file=${cfg_files[0]}
+  #         unset CSPELL_CFG_OPTION ; if [ -n "$cfg_file" ]; then CSPELL_CFG_OPTION="--config \"$cfg_file\"" ; fi
+  #         # * `cspell`
+  #         S=$(cspell ${CSPELL_CFG_OPTION} --no-summary --no-progress "**/*") && printf "%s\n" "$S" || { printf "%s\n" "$S" ; printf "%s" "$S" | sed -E -n "s/${PWD//\//\\/}\/(.*):(.*):(.*) - (.*)/::${fault_type} file=\1,line=\2,col=\3::${fault_type^^}: \4 (file:'\1', line:\2)/p" ; fault=true ; true ; }
+  #         if [ -n "${{ steps.vars.outputs.FAIL_ON_FAULT }}" ] && [ -n "$fault" ]; then exit 1 ; fi
 
   min_version:
     name: MinRustV # Minimum supported rust version (aka, MinSRV or MSRV)
